version: '3.9'

services:
  point_node:
    build:
      context: .
      dockerfile: Dockerfile
    image: point_node
    command: npm start
    depends_on:
      contract_deployer:
        condition: service_completed_successfully
      buckets:
        condition: service_completed_successfully
  test:
    image: point_node
    command: run test
    depends_on:
      - point_node
