version: '3.9'

services:
  point_node:
    image: pointnetwork/pointnetwork_node:$POINT_NODE_VERSION
    container_name: point_node
    volumes:
      - point_contracts:/app/truffle/build/contracts
      - point_node_data:/data
      - $POINT_KEYSTORE:/data/keystore
    ports:
      - '8666:8666'
      - '2468:2468'
    environment:
      NODE_ENV: production

volumes:
  point_contracts:
  point_node_data:
  database_data:
