version: '3.9'

services:
  point_node:
    image: ${POINT_DEV_IMAGE_NAME:-pointnetwork/pointnetwork_node:$POINT_NODE_VERSION}
    container_name: point_node
    volumes:
      - point_contracts:/app/hardhat/build/contracts
      - point_node_data:/data
      - $POINT_KEYSTORE:/data/keystore
      - $POINT_DEPLOYSPACE:/app/deployspace:ro
    environment:
      NODE_ENV: production

volumes:
  point_contracts:
  point_node_data:
