version: '3'

services:
  blockchain_node:
    image: trufflesuite/ganache-cli
    ports:
      - '$BLOCKCHAIN_PROVIDER_PORT:$BLOCKCHAIN_PROVIDER_PORT'
    volumes:
      - blockchain_data:/data:rw
    command:
      - -v
      - -p
      - $BLOCKCHAIN_PROVIDER_PORT
      - -m
      - $BLOCKCHAIN_PROVIDER_MNEMONIC
      - --db
      - '/data'
      - --account="$WEBSITE_OWNER_PRVKEY,$DEFAULT_BALANCE"
      - --account="$STORAGE_PROVIDER_PRVKEY,$DEFAULT_BALANCE"
      - --account="$TEST_PEER_PRVKEY,$DEFAULT_BALANCE"

  contract_deployer:
    image: pointnetwork/pointnetwork_deployer:dev
    depends_on:
      - blockchain_node
    deploy:
      restart_policy:
        condition: none
    volumes:
      - ${PWD}/truffle/truffle-config.js:/truffle/truffle-config.js:ro
      - ${PWD}/truffle/migrations:/truffle/migrations:ro
      - ${PWD}/truffle/contracts:/truffle/contracts:ro
      - ${PWD}/scripts/deploy-contracts-docker.js:/truffle/run.js:ro
      - shared_contracts:/build:rw
    entrypoint: /truffle/run.js
    environment:
      - BLOCKCHAIN_HOST=blockchain_node
      - BLOCKCHAIN_PORT=$BLOCKCHAIN_PROVIDER_PORT
      - COMPILER_VERSION=native
      - BUILD_PATH=/build

  storage_provider:
    image: pointnetwork/pointnetwork_node:dev
    depends_on:
      - blockchain_node
    entrypoint: './scripts/entrypoint-node.sh'
    command: '--datadir /data -v'
    volumes:
      - storage_provider_data:/data:rw
      - shared_contracts:/app/truffle/build/contracts:ro
      - ${PWD}/resources/demo2/config.test1.json:/nodeConfig.json:ro
      - ${PWD}/sharedConfig.json:/app/resources/defaultConfig.json:ro
    ports:
      - '12345:9685'
      - '65500:8666'
      - '24680:2468'

  website_owner:
    image: pointnetwork/pointnetwork_node:dev
    depends_on:
      - blockchain_node
    ports:
      - '12346:9685'
      - '65501:8666'
      - '24681:2468'
    entrypoint: './scripts/entrypoint-node.sh'
    command: '--datadir /data -v'
    volumes:
      - website_owner_data:/data:rw
      - shared_contracts:/app/truffle/build/contracts:ro
      - ${PWD}/resources/demo2/config.test2.json:/nodeConfig.json:ro
      - ${PWD}/sharedConfig.json:/app/resources/defaultConfig.json:ro

  website_visitor:
    image: pointnetwork/pointnetwork_node:dev
    depends_on:
      - blockchain_node
    ports:
      - '12347:9685'
      - '65502:8666'
      - '24682:2468'
    entrypoint: './scripts/entrypoint-node.sh'
    command: '--datadir /data -v'
    volumes:
      - website_visitor_data:/data:rw
      - shared_contracts:/app/truffle/build/contracts:ro
      - ${PWD}/resources/demo2/config.test3.json:/nodeConfig.json:ro
      - ${PWD}/sharedConfig.json:/app/resources/defaultConfig.json:ro

volumes:
  blockchain_data:
  shared_contracts:
  storage_provider_data:
  website_owner_data:
  website_visitor_data:
