version: '3.9'

services:
  storage_provider:
    volumes:
      - ./api:/app/api:ro
      - ./client:/app/client:ro
      - ./console:/app/console:ro
      - ./core:/app/core:ro
      - ./db:/app/db:ro
      - ./example:/app/example:ro
      - ./network:/app/network:ro
      - ./provider:/app/provider:ro
      - ./scripts:/app/scripts:ro
      - ./threads:/app/threads:ro
      - ./wallet:/app/wallet:ro
      - ./point:/app/point:ro
      - ./package.json:/app/package.json:ro

  website_owner:
    command: 'run start:docker:dev'
    volumes:
      - ./api:/app/api:ro
      - ./client:/app/client:ro
      - ./console:/app/console:ro
      - ./core:/app/core:ro
      - ./db:/app/db:ro
      - ./example:/app/example:ro
      - ./network:/app/network:ro
      - ./provider:/app/provider:ro
      - ./scripts:/app/scripts:ro
      - ./threads:/app/threads:ro
      - ./wallet:/app/wallet:ro
      - ./point:/app/point:ro
      - ./package.json:/app/package.json:ro

  website_visitor:
    command: 'run start:docker:dev'
    volumes:
      - ./api:/app/api:ro
      - ./client:/app/client:ro
      - ./console:/app/console:ro
      - ./core:/app/core:ro
      - ./db:/app/db:ro
      - ./example:/app/example:ro
      - ./network:/app/network:ro
      - ./provider:/app/provider:ro
      - ./scripts:/app/scripts:ro
      - ./threads:/app/threads:ro
      - ./wallet:/app/wallet:ro
      - ./point:/app/point:ro
      - ./package.json:/app/package.json:ro

  tests:
    image: pointnetwork/pointnetwork_node:$POINTNETWORK_NODE_VERSION
    container_name: pointnetwork_tests
    depends_on:
      - database
    entrypoint: 'npm'
    command: 'run test:db:docker'
    environment:
      - DATADIR=/data
      - BLOCKCHAIN_HOST=blockchain_node
      - BLOCKCHAIN_PORT=$BLOCKCHAIN_PROVIDER_PORT
      - BLOCKCHAIN_NETWORK_ID=$BLOCKCHAIN_NETWORK_ID
      - DATABASE_URL=postgres://pointuser:pointpass@database:5432/pointdb
    volumes:
      - ./db:/app/db:ro
      - ./api:/app/api:ro
      - ./core:/app/core:ro
      - ./tests:/app/tests:ro
      - ./client:/app/client:ro
      - ./wallet:/app/wallet:ro
      - ./console:/app/console:ro
      - ./example:/app/example:ro
      - ./network:/app/network:ro
      - ./scripts:/app/scripts:ro
      - ./threads:/app/threads:ro
      - ./provider:/app/provider:ro
      - ./package.json:/app/package.json:ro
      - ./resources/demo-docker/config.test2.json:/nodeConfig.json:ro
