version: '3'

services:
  peer_1:
    image: pointnetwork_node
    depends_on:
      - blockchain_provider
    volumes:
      - peer_1_data:/data:rw
      - ${PWD}/resources/demo/config.test1.json:/data/config.json:ro
    environment:
      - HOST=localhost
      - PORT=12345
      - PUB_KEY=$WEBSITE_OWNER_PUBKEY
      - PRV_KEY=$WEBSITE_OWNER_PRVKEY
      # - API_PORT
      # - ZPROXY_PORT
      # - BOOTSTRAP_NODE

  deployer:
    image: pointnetwork_deployer
    depends_on:
      - blockchain_provider
    volumes:
      - ${PWD}/truffle/truffle-config.js:/truffle/truffle-config.js:ro
      - ${PWD}/truffle/migrations:/truffle/migrations:ro
      - ${PWD}/truffle/contracts:/truffle/contracts:ro
      - ${PWD}/truffle.deploy.js:/truffle/run.js:ro
      - shared_contracts:/build:rw
    entrypoint:
      - /truffle/run.js
    environment:
      - BLOCKCHAIN_HOST=blockchain_provider
      - BLOCKCHAIN_PORT=$BLOCKCHAIN_PROVIDER_PORT
      - COMPILER_VERSION=native
      - BUILD_PATH=/build

  # peer2:
  #   build:
  #     context: .
  #     dockerfile: peer.Dockerfile
  #   link:
  #     - peer1
  #   volumes:
  #     - ./resources/demo/config.test2.json:/.point/config.json:ro

  # peer3:
  #   build:
  #     context: .
  #     dockerfile: peer.Dockerfile
  #   link:
  #     - peer1
  #   volumes:
  #     - ./resources/demo/config.test3.json:/.point/config.json:ro

  blockchain_provider:
    image: trufflesuite/ganache-cli
    ports:
      - "$BLOCKCHAIN_PROVIDER_PORT:$BLOCKCHAIN_PROVIDER_PORT"
    volumes:
      - blockchain_data:/data:rw
    command:
      - -v
      - -p
      - $BLOCKCHAIN_PROVIDER_PORT
      - -m
      - $BLOCKCHAIN_PROVIDER_MNEMONIC
      - --db
      - '/data'
      - --account="$WEBSITE_OWNER_PRVKEY,$DEFAULT_BALANCE"
      - --account="$STORAGE_PROVIDER_PRVKEY,$DEFAULT_BALANCE"
      - --account="$TEST_PEER_PRVKEY,$DEFAULT_BALANCE"

volumes:
  peer_1_data:
  shared_contracts:
  blockchain_data:
