version: '3.9'

services:
  storage_provider:
    volumes:
      - ./api:/app/api:ro
      - ./client:/app/client:ro
      - ./console:/app/console:ro
      - ./core:/app/core:ro
      - ./db:/app/db:ro
      - ./example:/app/example:ro
      - ./network:/app/network:ro
      - ./provider:/app/provider:ro
      - ./resources:/app/resources:ro
      - ./scripts:/app/scripts:ro
      - ./tests:/app/tests:ro
      - ./threads:/app/threads:ro
      - ./truffle:/app/truffle:ro
      - ./wallet:/app/wallet:ro
      - ./package.json:/app/package.json:ro
      - ./point:/app/point:ro

  website_owner:
    command: 'run start:docker:dev'
    volumes:
      - ./api:/app/api:ro
      - ./client:/app/client:ro
      - ./console:/app/console:ro
      - ./core:/app/core:ro
      - ./db:/app/db:ro
      - ./example:/app/example:ro
      - ./network:/app/network:ro
      - ./provider:/app/provider:ro
      - ./resources:/app/resources:ro
      - ./scripts:/app/scripts:ro
      - ./tests:/app/tests:ro
      - ./threads:/app/threads:ro
      - ./truffle:/app/truffle:ro
      - ./wallet:/app/wallet:ro
      - ./package.json:/app/package.json:ro
      - ./point:/app/point:ro

  website_visitor:
    command: 'run start:docker:dev'
    volumes:
      - ./api:/app/api:ro
      - ./client:/app/client:ro
      - ./console:/app/console:ro
      - ./core:/app/core:ro
      - ./db:/app/db:ro
      - ./example:/app/example:ro
      - ./network:/app/network:ro
      - ./provider:/app/provider:ro
      - ./resources:/app/resources:ro
      - ./scripts:/app/scripts:ro
      - ./tests:/app/tests:ro
      - ./threads:/app/threads:ro
      - ./truffle:/app/truffle:ro
      - ./wallet:/app/wallet:ro
      - ./package.json:/app/package.json:ro
      - ./point:/app/point:ro

  database:
    ports:
      - '5432:5432'

volumes:
  test_volume:
