version: '3.9'

services:
  point_node:
    extends:
      file: docker-compose.base.yaml
      service: point_node
    ports:
      - '8666:8666'
      - '2468:2468'

volumes:
  point_contracts:
  point_node_data:
