version: '3'

services:
  peer1:
    build:
      context: .
      dockerfile: peer.Dockerfile
    links:
      - blockchain_provider
    volumes:
      - ./resources/demo/config.test1.json:/config.json
      - ./peer.setup.js:/setup.js
      - volume1:/.point
    environment:
      - HOST=localhost
      - PORT=12345
      - PUB_KEY=$WEBSITE_OWNER_PUBKEY
      - PRV_KEY=$WEBSITE_OWNER_PRVKEY
      # - API_PORT
      # - ZPROXY_PORT
      # - BOOTSTRAP_NODE

  # peer2:
  #   build:
  #     context: .
  #     dockerfile: peer.Dockerfile
  #   link:
  #     - peer1
  #   volumes:
  #     - ./resources/demo/config.test2.json:/.point/config.json:ro

  # peer3:
  #   build:
  #     context: .
  #     dockerfile: peer.Dockerfile
  #   link:
  #     - peer1
  #   volumes:
  #     - ./resources/demo/config.test3.json:/.point/config.json:ro

  blockchain_provider:
    image: trufflesuite/ganache-cli
    ports:
      - "$BLOCKCHAIN_PROVIDER_PORT:$BLOCKCHAIN_PROVIDER_PORT"
    command:
      - -p
      - $BLOCKCHAIN_PROVIDER_PORT
      - -m
      - $BLOCKCHAIN_PROVIDER_MNEMONIC
      - --account="$WEBSITE_OWNER_PRVKEY,$DEFAULT_BALANCE"
      - --account="$STORAGE_PROVIDER_PRVKEY,$DEFAULT_BALANCE"
      - --account="$TEST_PEER_PRVKEY,$DEFAULT_BALANCE"

volumes:
  volume1:
  volume2:
  volume3:
