version: '3.9'

services:
  blockchain_node:
    hostname: blockchain_node
    extends:
        file: docker-compose.e2e.yaml
        service: blockchain_node

  contract_deployer:
    extends:
          file: docker-compose.e2e.yaml
          service: contract_deployer
    volumes:
      - shared_contracts_zappdev:/build:rw

  point_node:
    extends:
      file: docker-compose.base.yaml
      service: point_node
    depends_on:
      contract_deployer:
        condition: service_completed_successfully
    command: 'run start:zappdev'
    volumes:
      - ./config:/app/config:ro
      - ./example:/app/example:ro
      - ./internal:/app/internal:ro
      - ./migrations:/app/migrations:ro
      - ./resources:/app/resources:ro
      - ./scripts:/app/scripts:ro
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./nodemon.json:/app/nodemon.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - point_node_data_zappdev:/data
      - shared_contracts_zappdev:/app/hardhat/build
      - ./resources/blockchain-test-key.json:/data/keystore/key.json
      - ./resources/arweave-test-key.json:/data/keystore/arweave.json
    ports:
      - '12346:9685'
      - '65501:8666'
      - '24681:2468'
    environment:
      NODE_CONFIG_ENV: zappdev

  website_visitor:
    extends:
      file: docker-compose.base.yaml
      service: point_node
    container_name: website_visitor
    depends_on:
      contract_deployer:
        condition: service_completed_successfully
    command: 'run start:zappdev'
    volumes:
      - ./config:/app/config:ro
      - ./example:/app/example:ro
      - ./internal:/app/internal:ro
      - ./migrations:/app/migrations:ro
      - ./resources:/app/resources:ro
      - ./scripts:/app/scripts:ro
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./nodemon.json:/app/nodemon.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - website_visitor_data_zappdev:/data   
      - shared_contracts_zappdev:/app/hardhat/build
      - ./resources/blockchain-test-key2.json:/data/keystore/key.json
      - ./resources/arweave-test-key2.json:/data/keystore/arweave.json
    ports:
      - '12347:9685'
      - '65502:8666'
      - '24682:2468'
    environment:
      NODE_CONFIG_ENV: zappdev
      DATADIR: /data

  arlocal:
    image: textury/arlocal:v1.1.21
    container_name: arlocal
    command: node bin/index.js --persist=true
    ports:
      - '1984:1984'
    volumes:
      - arlocal_data:/home/node/:rw

volumes:
  blockchain_data_zappdev:
  shared_contracts_zappdev:
  point_node_data_zappdev:
  website_visitor_data_zappdev:
  arlocal_data:
