version: '3.9'

services:
  point_node:
    image: pointnode-local
    container_name: point_node
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 60s
    entrypoint: 'npm'
    command: 'run start:docker'
    volumes:
      - point_contracts:/app/truffle/build/contracts
      - point_node_data:/data
      - $POINT_KEYSTORE:/data/keystore
      - $POINT_DEPLOYSPACE:/app/deployspace:ro
    ports:
      - '8666:8666'
      - '2468:2468'
    environment:
      DATADIR: /data
      DB_ENV: production
      BLOCKCHAIN_URL: $BLOCKCHAIN_URL
      BLOCKCHAIN_NETWORK_ID: $BLOCKCHAIN_NETWORK_ID
      CONTRACT_ADDRESS_MIGRATIONS: $CONTRACT_ADDRESS_MIGRATIONS
      CONTRACT_ADDRESS_IDENTITY: $CONTRACT_ADDRESS_IDENTITY
      CONTRACT_ADDRESS_STORAGE_PROVIDER_REGISTRY: $CONTRACT_ADDRESS_STORAGE_PROVIDER_REGISTRY
      ARWEAVE_EXPERIMENT_VERSION_MINOR: $ARWEAVE_EXPERIMENT_VERSION_MINOR

volumes:
  point_contracts:
  point_node_data:
  database_data:
