version: '3'

services:
  blockchain_provider:
    build:
      context: .
      dockerfile: BCProvider.Dockerfile
      args:
        - WEBSITE_OWNER=$WEBSITE_OWNER_PUBKEY
        - STORAGE_PROVIDER=$STORAGE_PROVIDER_PUBKEY
        - TEST_PEER=$TEST_PEER_PUBKEY
        - BALANCE=$DEFAULT_BALANCE
        - PORT=$BLOCKCHAIN_PROVIDER_PORT
        - MNEMONIC=$BLOCKCHAIN_PROVIDER_MNEMONIC