version: '3.9'

services:
  arweave:
    image: lucaarweave/arweave-node:0.0.4
    container_name: point_storage
    hostname: arweave-node
    healthcheck:
      test: |
        wget -qO- http://localhost:1984/info
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
    ports:
      - '1984:1984'
    environment:
      AR_RUNMODE: test
    volumes:
      - ./resources/arweave-test-genesis.csv:/opt/arweave/data/genesis_wallets.csv
      - arweave_data:/mnt/arweave-data

  gateway:
    image: lucaarweave/arweave-gateway:0.0.1
    container_name: point_storage_gateway
    hostname: gateway
    volumes:
      - gateway_data:/app
    links:
      - gateway_db
      - arweave
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: gateway_db
      DATABASE_PORT: 5432
      POSTGRES_USER: arweave
      POSTGRES_PASSWORD: arweave
      POSTGRES_DB: arweave

  gateway_db:
    image: postgres:12
    container_name: point_storage_gateway_db
    hostname: gateway_db
    volumes:
      - gateway_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: arweave
      POSTGRES_PASSWORD: arweave
      POSTGRES_DB: arweave
    command: -p 5432

  bundler:
    image: pointnetwork/arweave-bundler:v1.0.0
    container_name: point_bundler
    hostname: bundler
    volumes:
      - ./resources/arweave-test-key.json:/app/keystore/key.json
    secrets:
      - minio_test_user
      - minio_test_pass
    environment:
      S3_HOST: bundler-cache
      S3_PORT: 9000
      S3_PROTOCOL: http
      S3_BUCKET: ' '
      S3_KEY_FILE: /run/secrets/minio_test_user
      S3_SECRET_FILE: /run/secrets/minio_test_pass
      ARWEAVE_HOST: arweave-node
      ARWEAVE_PORT: 1984
      ARWEAVE_PROTOCOL: http
      KEYSTORE: /app/keystore/key.json
      TESTMODE: '1'

  cache:
    image: minio/minio:RELEASE.2022-02-01T18-00-14Z
    container_name: point_storage_cache
    hostname: bundler-cache
    command: server /data --console-address ':9001'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - bundler_data:/data
    secrets:
      - minio_test_user
      - minio_test_pass
    environment:
      MINIO_ROOT_USER_FILE: /run/secrets/minio_test_user
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_test_pass

volumes:
  arweave_data:
  gateway_data:
  bundler_data:
  gateway_db_data:

secrets:
  minio_test_user:
    file: ./resources/minio_test_user
  minio_test_pass:
    file: ./resources/minio_test_pass
