version: '3.9'
services:
  point_node:
    volumes:
      - ./api:/app/api
      - ./client:/app/client
      - ./console:/app/console
      - ./core:/app/core
      - ./db:/app/db
      - ./debug:/app/debug
      - ./example:/app/example
      - ./internal:/app/internal
      - ./network:/app/network
      - ./provider:/app/provider
      - ./resources:/app/resources
      - ./scripts:/app/scripts
      - ./tests:/app/tests
      - ./threads:/app/threads
      - ./truffle:/app/truffle
      - ./wallet:/app/wallet
      - ./package.json:/app/package.json
      - ./point:/app/point
