version: '3.9'

services:
  blockchain_node:
    image: trufflesuite/ganache-cli:v6.12.2
    container_name: point_blockchain
    hostname: blockchain_node
    healthcheck:
      test: |
        wget -qO- http://localhost:7545 \
          --header='Content-Type: application/json' \
          --header="Accept: application/json" \
          --post-data='{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":0}'
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
    ports:
      - '7545:7545'
    volumes:
      - blockchain_data_e2e:/data:rw
    environment:
      - DOCKER=true
    command: |
      -v -p 7545 -i 256 --keepAliveTimeout 20000 --db /data \
        --account 0x011967d88c6b79116bb879d4c2bc2c3caa23569edd85dfe0bc596846837bbc8e,0x56bc75e2d63100000

  contract_deployer:
    image: pointnetwork/pointnetwork_deployer:dev
    container_name: point_deployer
    depends_on:
      blockchain_node:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: 'no'
    volumes:
      - shared_contracts_e2e:/build:rw
      - ./truffle/contracts:/truffle/contracts:ro
      - ./truffle/migrations:/truffle/migrations:ro
      - ./truffle/truffle-config.js:/truffle/truffle-config.js:ro
    entrypoint: /truffle/run.js
    environment:
      BLOCKCHAIN_HOST: blockchain_node
      BLOCKCHAIN_PORT: 7545
      BLOCKCHAIN_NETWORK_ID: 256
      DEPLOYER_COMPILER_VERSION: native
      DEPLOYER_BUILD_PATH: /build

  point_node:
    extends:
      file: docker-compose.dev.yaml
      service: point_node
    depends_on:
      contract_deployer:
        condition: service_completed_successfully
    volumes:
      - point_node_data_e2e:/data
      - shared_contracts_e2e:/app/truffle/build/contracts
      - ./resources/blockchain-test-key.json:/data/keystore/key.json
      - ./resources/arweave-test-key.json:/data/keystore/arweave.json
    environment:
      ARWEAVE_BUNDLER_URL: http://bundler:80
      ARWEAVE_GATEWAY_URL: http://gateway:3000
      BLOCKCHAIN_URL: http://blockchain_node:7545

  arweave:
    extends:
      file: docker-compose.storage.yaml
      service: arweave
    volumes:
      - arweave_data_e2e:/mnt/arweave-data

  gateway:
    extends:
      file: docker-compose.storage.yaml
      service: gateway
    volumes:
      - gateway_data_e2e:/app

  gateway_db:
    extends:
      file: docker-compose.storage.yaml
      service: gateway_db
    volumes:
      - gateway_db_data_e2e:/var/lib/postgresql/data

  bundler:
    extends:
      file: docker-compose.storage.yaml
      service: bundler
    depends_on:
      arweave:
        condition: service_healthy
    volumes:
      - ../arweave-bundler/src:/app/src
      - ../arweave-bundler/config:/app/config
    entrypoint: npx
    command: nodemon --watch ./**/* --ext "ts,yaml" --exec "ts-node src/index.ts"

  cache:
    extends:
      file: docker-compose.storage.yaml
      service: cache
    volumes:
      - bundler_data_e2e:/data

  createbuckets:
    image: minio/mc
    container_name: point_bucket
    depends_on:
      cache:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://bundler-cache:9000 miniouser miniopass &&
      /usr/bin/mc mb minio/testbucket &&
      /usr/bin/mc policy set public minio/testbucket &&
      exit 0;
      "

volumes:
  blockchain_data_e2e:
  shared_contracts_e2e:
  point_node_data_e2e:
  arweave_data_e2e:
  gateway_data_e2e:
  bundler_data_e2e:
  gateway_db_data_e2e:
