version: '3.9'

services:
  point_node:
    extends:
      file: docker-compose.yaml
      service: point_node
    command: 'run start:dev'
    volumes:
      - point_contracts_dev:/data/hardhat/artifacts/contracts:rw
      - point_node_data_dev:/data
      - ./config:/app/config:ro
      - ./example:/app/example:ro
      - ./internal:/app/internal:ro
      - ./migrations:/app/migrations:ro
      - ./resources:/app/resources:ro
      - ./scripts:/app/scripts:ro
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./nodemon.json:/app/nodemon.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
    environment:
      NODE_CONFIG_ENV: dockerdev

volumes:
  point_contracts_dev:
  point_node_data_dev:
