datadir: /data
mode: e2e
log:
  level: debug
storage:
  arweave_experiment_version_major: 123
  arweave_experiment_version_minor: 456
  arweave_bundler_url: http://bundler:80
  arweave_gateway_url: http://gateway:3000
network:
  web3: http://blockchain_node:7545
