name: Git-Job-Staging-FrontEnd-Deployment
on:
  push:
    branches:
      - image-build-automation # TODO: temp
    # tags:
    #   - 'v*'


# env:
#   REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
#   REGISTRY_PASS: ${{ secrets.REGISTRY_PASS }}

jobs:
  deploy:
    runs-on: macos-11.0
    env:
      IMAGE_NAME: pointnetwork/pointnetwork_node
    steps:
      - uses: actions/checkout@v1
      # - name: docker login
      #   run: docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
      - name: Get the Source Tag
        id: get_source_tag
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Test Tag
        run: 'echo "The source tag is: ${{ steps.get_source_tag.outputs.SOURCE_TAG }}"'
      - name: Build the Image
        run: docker build -t "${{ env.IMAGE_NAME }}:dev" . # TODO: replace 'dev' tag with a version recieved in the git tag
      # - name: Publish the Image
      #   run: docker push "${{ env.IMAGE_NAME }}:${{ steps.get_source_tag.outputs.SOURCE_TAG }}"
      - name: Done
        run: echo Done.
